{
 "title": "DSSNService",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Read RPC Handler Latency (usec)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "DSSNService_Tracing_sum{label=\"read\"}/DSSNService_Tracing_count{label=\"read\"}"
    }
   ]
  },
  {
   "title": "Read MultiOp RPC  Handler Latency (usec)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "DSSNService_Tracing_sum{label=\"read_multiops\"}/DSSNService_Tracing_count{label=\"read_multiops\"}"
    }
   ]
  },
  {
   "title": "DSSNInfo RPC Handler Latency (usec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "DSSNService_Tracing_sum{label=\"recv_dssninfo\"}/DSSNService_Tracing_count{label=\"recv_dssninfo\"}"
    }
   ]
  },
  {
   "title": "DSSNInfo Request RPC Handler Latency (usec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "DSSNService_Tracing_sum{label=\"recv_dssninfo_request\"}/DSSNService_Tracing_count{label=\"recv_dssninfo_request\"}"
    }
   ]
  },
  {
   "title": "Send Tx Reply Latency (usec)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "DSSNService_Tracing_sum{label=\"send_txreply\"}/DSSNService_Tracing_count{label=\"send_txreply\"}"
    }
   ]
  },
  {
   "title": "Send DSSN Info Latency (usec)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "DSSNService_Tracing_sum{label=\"send_dssninfo\"}/DSSNService_Tracing_count{label=\"send_dssninfo\"}"
    }
   ]
  },
  {
   "title": "Request DSSN Info Latency (usec)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "DSSNService_Tracing_sum{label=\"send_dssninfo_request\"}/DSSNService_Tracing_count{label=\"send_dssninfo_request\"}"
    }
   ]
  },
  {
   "title": "Commit  RPC  Handler Latency (usec)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "DSSNService_Tracing_sum{label=\"commit\"}/DSSNService_Tracing_count{label=\"commit\"}"
    }
   ]
  },
  {
   "title": "Read KV RPC  Handler Latency (usec)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "DSSNService_Tracing_sum{label=\"read_kv\"}/DSSNService_Tracing_count{label=\"read_kv\"}"
    }
   ]
  },
  {
   "title": "Write RPC  Handle",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "DSSNService_Tracing_sum{label=\"write\"}/DSSNService_Tracing_count{label=\"write\"}"
    }
   ]
  },
  {
   "title": "Write MultiOp RPC  Handler Latency (usec)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "DSSNService_Tracing_bucket_sum{label=\"write_multiops\"}/DSSNService_Tracing_count{label=\"write_multiops\"}"
    }
   ]
  },
  {
   "title": "Transaction Diagnostic (reqs/sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "DSSNService_diagnostic{label=\"read_multiops\"}"
    },
    {
     "expr": "DSSNService_diagnostic{label=\"commit\"}"
    },
    {
     "expr": "DSSNService_diagnostic{label=\"send_txreply\"}"
    }
   ]
  },
  {
   "title": "DSSN Info Exchange Diagnostic (req/sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "DSSNService_diagnostic{label=\"send_dssninfo\"}"
    },
    {
     "expr": "DSSNService_diagnostic{label=\"recv_dssninfo\"}"
    },
    {
     "expr": "DSSNService_diagnostic{label=\"send_dssninfo_request\"}"
    },
    {
     "expr": "DSSNService_diagnostic{label=\"recv_dssninfo_request\"}"
    }
   ]
  }
 ]
}