{
 "title": "WorkerManager",
 "description": "WorkerManager Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RPC Latency (usec)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workermanager_rpc_latency_sum{label=\"RPC_total_latency\"}/workermanager_rpc_latency_count{label=\"RPC_total_latency\"}"
    }
   ]
  },
  {
   "title": "RPC PreProcessing Latency (usec)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workermanager_rpc_latency_sum{label=\"RPC_preprocessing_latency\"}/workermanager_rpc_latency_count{label=\"RPC_preprocessing_latency\"}"
    }
   ]
  },
  {
   "title": "Ingress Queueing Latency (usec)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workermanager_rpc_latency_sum{label=\"RPC_ingress_latency\"}/workermanager_rpc_latency_count{label=\"RPC_ingress_latency\"}"
    }
   ]
  },
  {
   "title": "RPC Processing Queuing Latency (usec)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workermanager_rpc_latency_sum{label=\"RPC_processing_queue_latency\"}/workermanager_rpc_latency_count{label=\"RPC_processing_queue_latency\"}"
    }
   ]
  },
  {
   "title": "Egress Queueing Latency (usec)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workermanager_rpc_latency_sum{label=\"RPC_egress_latency\"}/workermanager_rpc_latency_count{label=\"RPC_egress_latency\"}"
    }
   ]
  },
  {
   "title": "RPC Processing Latency (usec)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workermanager_rpc_latency_sum{label=\"RPC_processing_latency\"}/workermanager_rpc_latency_count{label=\"RPC_processing_latency\"}"
    }
   ]
  },
  {
   "title": "Diagnostic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "workermanager_diagnostic" }
   ]
  },
  {
   "title": "Incoming RPC Rate (req/sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(workermanager_performance)", "legendFormat": "total" },
    { "expr": "workermanager_performance" }
   ]
  },
  {
   "title": "Worker Handoff Latency (usec)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workermanager_rpc_latency_sum{label=\"RPC_worker_handoff_latency\"}/workermanager_rpc_latency_count{label=\"RPC_worker_handoff_latency\"}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load15" }
   ]
  },
  {
   "title": "Dispatcher Poll Latency (usec)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workermanager_rpc_latency_sum{label=\"worker_manager_poll_latency\"}/workermanager_rpc_latency_count{label=\"worker_manager_poll_latency\"}\n"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes" }
   ]
  }
 ]
}