#!/bin/bash

# Copyright 2020 Futurewei Technologies, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

pidfile=/dev/shm/.$USER.$1.pid
pid=$(cat $pidfile 2>/dev/null)
cnt=0
while [ -z $pid ]; do
    ((cnt++))
    if [ $cnt -eq 1000 ]; then
	exit 0
    fi
    sleep .01
    pid=$(cat $pidfile 2>/dev/null)
done
rm -f $pidfile
kill $pid 2>/dev/null || exit 0
cnt=0
while true; do
    ((cnt++))
    if [ $cnt -eq 1000 ]; then
	exit 0
    fi
    sleep .01
    kill $pid 2>/dev/null || exit 0
done
