#!/bin/bash

# Copyright 2020 Futurewei Technologies, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Usage: killserver kill_on_exit wd file
# First change to the working directory.
# If kill_on_exit == 1, only then clean up this server.

cd $2
file=$3
if [[ "$1" == "1" ]]; then
    # kill the server
    # extracting the pid as a substring of the file name - rcxx_pid
    pid=${file#*_}
    rm -rf logs/shm/$file

    kill $pid 2>/dev/null || exit 0
    cnt=0
    while true; do
	((cnt++))
	if [ $cnt -eq 1000 ]; then
		exit 0
	fi
        sleep .01
        kill $pid 2>/dev/null || exit 0
    done
fi
