add_library(ramcloud SHARED "")
target_sources(ramcloud
  PRIVATE
  AbstractLog.cc
  AbstractServerList.cc
  AdminClient.cc
  AdminService.cc
  ArpCache.cc
  BasicTransport.cc
  CacheTrace.cc
  ClientException.cc
  ClientLeaseAgent.cc
  ClientTransactionManager.cc
  ClientTransactionTask.cc
  Context.cc
  CoordinatorClient.cc
  CoordinatorRpcWrapper.cc
  CoordinatorSession.cc
  CRamCloud.cc
  Crc32C.cc
  BackupClient.cc
  BackupFailureMonitor.cc
  BackupSelector.cc
  Buffer.cc
  CleanableSegmentManager.cc
  ClientException.cc
  ClusterMetrics.cc
  CodeLocation.cc
  Common.cc
  Cycles.cc
  DataBlock.cc
  Dispatch.cc
  DispatchExec.cc
  Driver.cc
  ZooStorage.cc
  HashEnumeration.cc
  HashEnumerationIterator.cc
  ExternalStorage.cc
  FailureDetector.cc
  FailSession.cc
  FileLogger.cc
  HashObjectManager.cc
  HashTable.cc
  HomaTransport.cc
  dssn/HOTKV.cc
  IndexKey.cc
  IndexletManager.cc
  IndexLookup.cc
  IndexRpcWrapper.cc
  IpAddress.cc
  Key.cc
  LargeBlockOfMemory.cc
  LinearizableObjectRpcWrapper.cc
  LockTable.cc
  Log.cc
  LogCabinLogger.cc
  LogCabinStorage.cc
  LogCleaner.cc
  LogDigest.cc
  LogEntryRelocator.cc
  LogEntryTypes.cc
  LogMetricsStringer.cc
  LogProtector.cc
  Logger.cc
  LogIterator.cc
  MacAddress.cc
  MacIpAddress.cc
  MasterClient.cc
  MasterService.cc
  MasterTableMetadata.cc
  Memory.cc
  MemoryMonitor.cc
  MinCopysetsBackupSelector.cc
  MultiOp.cc
  MultiIncrement.cc
  MultiRead.cc
  MultiRemove.cc
  MultiWrite.cc
  MurmurHash3.cc
  NetUtil.cc
  Notifier.cc
  Object.cc
  ObjectBuffer.cc
  ObjectFinder.cc
  ObjectRpcWrapper.cc
  OptionParser.cc
  ParticipantList.cc
  PcapFile.cc
  PerfCounter.cc
  PerfStats.cc
  PlusOneBackupSelector.cc
  PortAlarm.cc
  PreparedOp.cc
  RamCloud.cc
  RawMetrics.cc
  ReplicaManager.cc
  ReplicatedSegment.cc
  RpcLevel.cc
  RpcWrapper.cc
  RpcResult.cc
  RpcTracker.cc
  Seglet.cc
  SegletAllocator.cc
  Segment.cc
  SegmentIterator.cc
  SegmentManager.cc
  ServerIdRpcWrapper.cc
  ServerList.cc
  ServerMetrics.cc
  Service.cc
  ServiceLocator.cc
  SessionAlarm.cc
  SideLog.cc
  SpinLock.cc
  Status.cc
  StringUtil.cc
  Tablet.cc
  TableEnumerator.cc
  TableStats.cc
  TabletManager.cc
  TaskQueue.cc
  TcpTransport.cc
  TestLog.cc
  ThreadId.cc
  TimeCounter.cc
  TimeTrace.cc
  TimeTraceUtil.cc
  TpcC.cc
  Transaction.cc
  TransactionManager.cc
  Transport.cc
  TransportManager.cc
  TxDecisionRecord.cc
  TxRecoveryManager.cc
  UdpDriver.cc
  UnackedRpcResults.cc
  Util.cc
  WallTime.cc
  WireFormat.cc
  WorkerManager.cc
  WorkerSession.cc
  WorkerTimer.cc
  ${PROTO_SRCS}${PROTO_HDRS})
